-- Active: 1745889706777@@127.0.0.1@3306@employees

-- 사원번호, 이름, 부서명을 조회하시오.
-- employees, dept_emp, departments
SELECT E.EMP_NO
, E.FIRST_NAME
, EMP.DEPT_NO
, D.DEPT_NAME
FROM EMPLOYEES E
, DEPT_EMP EMP 
, DEPARTMENTS D 
WHERE E.EMP_NO = EMP.EMP_NO
  AND EMP.DEPT_NO = D.DEPT_NO;

-- inner join을 사용하여 조회
SELECT E.EMP_NO
, E.FIRST_NAME
, EMP.DEPT_NO
, D.DEPT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPT_EMP EMP 
       ON E.EMP_NO = EMP.EMP_NO
LEFT JOIN DEPARTMENTS D 
       ON EMP.DEPT_NO = D.DEPT_NO;
