-- Active: 1745889706777@@127.0.0.1@3306@aloha

-- 부서가 없는 사원도 출력
SELECT E.EMP_NO, E.name, D.DEPT_NO, D.DEPT_NAME
FROM EMPLOYEES E
    LEFT JOIN DEPARTMENT D 
    ON E.DEPT_NO = D.DEPT_NO

-- 부서에 사원이 존재 하지 않는 경우에도 출력한다.
SELECT E.EMP_NO, E.name, D.DEPT_NO, D.DEPT_NAME
FROM EMPLOYEES E
    RIGHT JOIN DEPARTMENT D 
    ON E.DEPT_NO = D.DEPT_NO

-- 부서가 없는 사원도, 사원이 없는 부서도 출력
SELECT E.EMP_NO, E.name, D.DEPT_NO, D.DEPT_NAME
FROM EMPLOYEES E
    LEFT JOIN DEPARTMENT D 
    ON E.DEPT_NO = D.DEPT_NO
UNION
SELECT E.EMP_NO, E.name, D.DEPT_NO, D.DEPT_NAME
FROM EMPLOYEES E
    RIGHT JOIN DEPARTMENT D 
    ON E.DEPT_NO = D.DEPT_NO

    