-- ACTIVE: 1745889706777@@127.0.0.1@3306@ALOHA
-- ACTIVE: 1745889706777@@127.0.0.1@3306@EMPLOYEES
-- 스칼라 서브쿼리
-- 사원 테이블의 가장 높은 급여를 조회
SELECT EMP_NO, NAME, (
        SELECT MAX(SALARY)
        FROM EMPLOYEES
    ) AS '최대급여'
FROM EMPLOYEES

-- 인라인뷰
-- 급여가 400이상인 사원의 사원번호, 이름, 부서명을 출력하시오
SELECT E.EMP_NO, E.NAME, E.DEPT_NO
FROM (
        SELECT *
        FROM EMPLOYEES
        WHERE
            SALARY >= 400
    ) E
    JOIN DEPARTMENT D ON E.DEPT_NO = D.DEPT_NO

-- 서브쿼리
-- 각 부서별로 가장 높은 급여를 가진 사원의 이름과  급여를 조회하시오
SELECT D.DEPT_NAME, E.NAME, E.SALARY
FROM EMPLOYEES E, DEPARTMENT D
WHERE E.DEPT_NO = D.DEPT_NO
AND (E.DEPT_NO, E.SALARY) IN 
(SELECT DEPT_NO, MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPT_NO) 


SELECT ROW_NUMBER() OVER() FROM EMPLOYEES