-- Active: 1745889706777@@127.0.0.1@3306@sakila
-- Active: 1745889706777@@127.0.0.1@3306@test_db-- Active: 1745889706777@@127.0.0.1@3306@test_db
-- 테이블 생성
/*
CREATE TABLE 데이터베이스.테이블명 (
  컬럼1 데이터타입 [NULL/NOT NULL] [DEFAULT 기본값] [PRIMARY KEY | UNIQUE] [COMMENT '컬럼 설명'],
                   NULL            NULL 
  컬럼2 데이터타입 [NULL/NOT NULL] [DEFAULT 기본값] [PRIMARY KEY | UNIQUE] [COMMENT '컬럼 설명'],
  컬럼3 데이터타입 [NULL/NOT NULL] [DEFAULT 기본값] [PRIMARY KEY | UNIQUE] [COMMENT '컬럼 설명']
) COMMENT '테이블설명' ;
*/

CREATE TABLE COMMON (
  `NO` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'PK',
  `ID` VARCHAR(64) UNIQUE  COMMENT 'UK',
  `NAME` VARCHAR(100) NOT NULL COMMENT '이름',
  `VALUE` INT NOT NULL DEFAULT 0 COMMENT '값',
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
  /* 컬럼의 데이터가 변경 될 때마다 날짜 업데이트*/
  ON UPDATE CURRENT_TIMESTAMP 
  COMMENT '수정일'
) COMMENT '테이블'


-- 기존 테이블을 복사하여 생성(백업 테이블 생성)
CREATE TABLE STAFF_BACKUP
AS SELECT * FROM STAFF ;

-- 기존 테이블을 일부 데이터만 복사하여 생성
CREATE TABLE STAFF_BACKUP2
AS SELECT first_name, last_name FROM STAFF ;

-- 테이블 수정
-- 컬럼 추가
ALTER TABLE STAFF_BACKUP2 
ADD COLUMN NO BIGINT AUTO_INCREMENT PRIMARY KEY ;

-- 컬럼 수정
ALTER TABLE STAFF_BACKUP
MODIFY COLUMN address_ID BIGINT;

-- 컬럼 삭제
ALTER TABLE STAFF_BACKUP2
DROP COLUMN last_name;



---  테이블 삭제
SELECT * FROM STAFF_BACKUP2

