USE bbs ;

DROP DATABASE IF EXISTS `community` ;

CREATE DATABASE `community`
    DEFAULT CHARACTER SET = 'utf8mb4';

USE community ;

DROP TABLE IF EXISTS `FILES`;
DROP TABLE IF EXISTS `COMMENTS`;
DROP TABLE IF EXISTS `POSTS`;
DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
	`NO`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT '회원번호',
	`ID`	VARCHAR(64)	NOT NULL UNIQUE	COMMENT 'UK',
	`USERNAME`	VARCHAR(100)	NOT NULL UNIQUE	COMMENT '아이디',
	`PASSWORD`	VARCHAR(100)	NOT NULL	COMMENT '비밀번호',
	`NAME`	VARCHAR(50)	NOT NULL	COMMENT '이름',
	`EMAIL`	VARCHAR(200)	NOT NULL	COMMENT '이메일',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '회원' ;

CREATE TABLE `POSTS` (
	`NO`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT '게시글 번호',
	`ID`	VARCHAR(64)	NOT NULL UNIQUE	COMMENT 'UK',
	`USER_NO`	BIGINT	NOT NULL	COMMENT '회원번호',
	`TITLE`	VARCHAR(100)	NOT NULL	COMMENT '제목',
	`CONTENT`	TEXT	NULL	COMMENT '내용',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	Foreign Key (`USER_NO`) REFERENCES `USERS`(`NO`)
) COMMENT '게시글' ;

CREATE TABLE `COMMENTS` (
	`NO`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT '댓글 번호',
	`ID`	VARCHAR(64)	NOT NULL UNIQUE	COMMENT 'UK',
	`POST_NO`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`USER_NO`	BIGINT	NOT NULL	COMMENT '회원번호',
	`CONTENT`	TEXT	NOT NULL	COMMENT '내용',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	Foreign Key (`USER_NO`) REFERENCES `USERS`(`NO`),
	Foreign Key (`POST_NO`) REFERENCES `POSTS`(`NO`)
) COMMENT '댓글' ;

CREATE TABLE `FILES` (
	`NO`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT '파일 번호',
	`ID`	VARCHAR(64)	NOT NULL UNIQUE	COMMENT 'UK',
	`POST_NO`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`FILE_NAME`	VARCHAR(100)	NOT NULL	COMMENT '파일명',
	`FILE_PATH`	VARCHAR(100)	NOT NULL	COMMENT '파일 경로',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자',
	Foreign Key (`POST_NO`) REFERENCES `POSTS`(`NO`)
) COMMENT '파일' ;

