DROP DATABASE IF EXISTS `community` ;

CREATE DATABASE `community`
    DEFAULT CHARACTER SET = 'utf8mb4';

USE community ;

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
	`NO`	BIGINT	NOT NULL	COMMENT '회원번호',
	`ID`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`USERNAME`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`PASSWORD`	VARCHAR(100)	NOT NULL	COMMENT '비밀번호',
	`NAME`	VARCHAR(50)	NOT NULL	COMMENT '이름',
	`EMAIL`	VARCHAR(200)	NOT NULL	COMMENT '이메일',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);

DROP TABLE IF EXISTS `Board`;

CREATE TABLE `Board` (
	`NO`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`ID`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '회원번호',
	`TITLE`	VARCHAR(100)	NOT NULL	COMMENT '제목',
	`CONTENT`	TEXT	NULL	COMMENT '내용',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);

DROP TABLE IF EXISTS `FILES`;

CREATE TABLE `FILES` (
	`NO`	BIGINT	NOT NULL	COMMENT '파일 번호',
	`ID`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`POSTS_NO`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`FILE_NAME`	VARCHAR(100)	NOT NULL	COMMENT '파일명',
	`FILE_PATH`	VARCHAR(100)	NOT NULL	COMMENT '파일 경로',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);
DROP TABLE IF EXISTS `COMMENTS`;

CREATE TABLE `COMMENTS` (
	`NO`	BIGINT	NOT NULL	COMMENT '댓글 번호',
	`ID`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`POSTS_NO`	BIGINT	NOT NULL	COMMENT '게시글 번호',
	`USER_ID`	BIGINT	NOT NULL	COMMENT '회원번호',
	`CONTENT`	TEXT	NOT NULL	COMMENT '내용',
	`CREATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`UPDATE_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`NO`
);

ALTER TABLE `FILES` ADD CONSTRAINT `PK_FILES` PRIMARY KEY (
	`NO`
);

ALTER TABLE `Board` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`NO`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `PK_COMMENTS` PRIMARY KEY (
	`NO`
);

ALTER TABLE `FILES` ADD CONSTRAINT `FK_Board_TO_FILES_1` FOREIGN KEY (
	`POSTS_NO`
)
REFERENCES `Board` (
	`NO`
);

ALTER TABLE `Board` ADD CONSTRAINT `FK_USERS_TO_Board_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`NO`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `FK_Board_TO_COMMENTS_1` FOREIGN KEY (
	`POSTS_NO`
)
REFERENCES `Board` (
	`NO`
);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `FK_USERS_TO_COMMENTS_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USERS` (
	`NO`
);

